### ISSUE TITLE
相较之前版本有变动么？上次fork的不是这个版本的啊，上次的版本star和fork都200+了

### ISSUE THREAD

**Issue by ax3353** [xlorne/tx-lcn#1]
相较之前版本有变动么？上次fork的不是这个版本的啊，上次的版本star和fork都好几百了

**Comment by xlorne** [comment]
没有变动，框架代码之前提交过300多次，里面很多日志是没用的，主要是之前提交过多次war文件，导致项目的git log日志特别庞大。超过200多m，这样大家在clone代码的时候很不方便。 我现在将lcn项目删除了， 然后重新建了。
